### ISSUE TITLE
Can't start stream

### ISSUE THREAD

**Issue by smokecustom** [AlexxIT/WebRTC#1]
Logger: custom_components.webrtc
Source: custom_components/webrtc/__init__.py:111
Integration: WebRTC Camera (documentation, issues)
First occurred: 23:04:27 (12 occurrences)
Last logged: 23:24:55

Can't start stream: rtsp://192.168.1.116:554/onvif1, because: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://localhost:8083/stream')

Well, can't imagine something else. But VLC player CAN open stream and show it right way.. Where should I start search problem?

**Comment by AlexxIT** [comment]
Maybe 8083 port occupied on server with some utility

**Comment by smokecustom** [comment]
Noop, no bynny at all..
ss -tulpn shown only this:
...
tcp    LISTEN  0  4096  127.0.0.1:8083  0.0.0.0:*  users:(("rtsp2webrtc_v1_",pid=46044,fd=6))
...

**Comment by smokecustom** [comment]
After update to v1.0.2 everything works just fine... I installed and updated component via HACS, so, I'm not really sure, what hapepenned.

**Comment by colethegamer123** [comment]
I have the same issue on v1.0.2. First I installed and restarted HA it was working perfectly, I wanted to re-create a card now in the good place and with conditional card, but now it just loads forever, I got the same log entry:

`Can't start stream: rtsp://myuser:mypassword@192.168.0.62/ch0_0.h264, because: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://localhost:8083/stream')`

Thank you my friend.
