### ISSUE TITLE
Custom Element does not exist after 2.0.2 on old ipad. 

### ISSUE THREAD

**Issue by 7michaelg7** [AlexxIT/WebRTC#107]
A couple weeks ago I started getting the "Custom element doesn't exist: webrtc-camera" error on my iPad air 2 running iOS 12.5.4. The most updated version works perfectly everywhere except the iPad. I have reverted to the 2.0.2 version of the integration and everything works fine. 

This thread seems to suggest it might be an issue with external resources: https://community.home-assistant.io/t/stuck-on-custom-element-doesnt-exist-need-help/73220/43

Thanks!

**Comment by milkplus27** [comment]
Am having the same issue on an iPad Mini 2 (well, several actually) running 12.5.4

**Comment by fouram** [comment]
This is also happening to me on iOS devices since the update (my main driver is iPhone 6 on iOS 12.5.4; have some newer with iOS 14, need to check them). I have attempted to reset the frontend cache in the app, as well as reinstalling the app entirely and wiping all Safari data. I've tried re-installing webrtc-camera (but NOT downgrading). HomeAssistant has been restarted several times, including for core version upgrades and also the entire host. There is a reverse proxy being used on another machine that has also been restarted, and is not configured to cache in any way.

The logs are full of entries like this:
`2021-07-13 10:21:17 ERROR (MainThread) [frontend.js.latest.202107070] https://<my.homeassistant.instance>/webrtc/webrtc-camera.js?v2.0.2:88:0 InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable`

So it looks like, for some reason, iOS is caching that version number? Not sure why I can't reload Lovelace and fix this...

**Comment by stripeyhorse** [comment]
Having this issue as well , but i am using a iPad Pro. It works on my android phone and all pcs just fine , but on the ipad (tried safari , edge and chrome) and the home assistant app i get the customer element does not exist.

**Comment by AlexxIT** [comment]
This issue maybe fixed in latest master version

**Comment by milkplus27** [comment]
> This issue maybe fixed in latest master version

hi. you mean on 2.1.1?

**Comment by AlexxIT** [comment]
No, the master version does not have a number

**Comment by milkplus27** [comment]
> No, the master version does not have a number

Ah ok. So how do I update to the master version from HACS?

**Comment by milkplus27** [comment]
Oh, my bad. I found it in the drop-down. Trying now. Thanks for the heads up

**Comment by 7michaelg7** [comment]
> Oh, my bad. I found it in the drop-down. Trying now. Thanks for the heads up

Would you mind telling me where you found this dropdown? I would like to try as well.

**Comment by milkplus27** [comment]
So far so good for me. Thanks @AlexxIT for looking into this.

**Comment by AlexxIT** [comment]
Fixed long time ago
