### ISSUE TITLE
Dashcast audio disabled

### ISSUE THREAD

**Issue by jemershaw** [AlexxIT/WebRTC#129]
Is it possible to stream with dashcast with audio enabled? It seems like whatever is streamed it is disabled. I tried adding `muted: false` when running dashcast but that didn't help.

**Comment by Shermer321** [comment]
I have a dahua camera that is also always muted and the button is grayed out. Am I missing something?

**Comment by felipecrs** [comment]
There should be a way around it... the go2rtc player comes unmuted by default. No?

**Comment by felipecrs** [comment]
Anyway, the best possible thing would be to stream directly to the cast receiver by using WebRTC.

All Google Cast devices are able to play WebRTC media, I just don't know how this could be implemented.

**Comment by felipecrs** [comment]
https://github.com/castjs/castjs

Maybe this could help.

**Comment by AlexxIT** [comment]
go2rtc will try to play with sound. But browser can block it. If user not interact with it earlier. And no one interact with Chromecast.

**Comment by felipecrs** [comment]
I see. That's very odd!

BTW I just had a crazy idea here. What if instead of relying on Chromecast's built-in browser, we could spin-up a browser in the server-side with Puppeteer, and use Chrome's APIs to cast a page (like the go2rtc web player). This is probably doable.

https://github.com/SamuelScheit/puppeteer-stream

The question is whether this is worth it or not, versus trying to make the stream happen directly in Chromecast without rendering it through a browser.
