### ISSUE TITLE
Custom element doesn't exist: webrtc-camera

### ISSUE THREAD

**Issue by TomHart** [AlexxIT/WebRTC#140]
All of a sudden the webrtc card has stopped working. It's requesting the URL `https://my.homeassistant.domain/webrtc/webrtc-camera.js?v2.0.2`

This is the files I have locally

```
[core-ssh ~]$ find / -name *webrtc*
/config/rtsp2webrtc_v4_amd64
/config/custom_components/webrtc
/config/custom_components/webrtc/www/webrtc-camera.js
/config/custom_components/webrtc/www/webrtc-camera.js.gz
```

Do you know why it might have stopped working?

I've tried all the usual steps of re-installing the integration, installing a previous version, restarting home-assistant etc

**Comment by JKSTAFF** [comment]
Same issue after update HA to v2021.10.4 . Also try Q&A step but not working

**Comment by Sholofly** [comment]
Same here. Probably issue with te file reference?

**Comment by boctok** [comment]
I am having issues with a newly setup integration. I do have the integration installed from the Configuration page. I do have debug logging set. I do not see any error messages in the logs, but I am still getting "Custom element doesn't exist: webrtc-camera" messages when I try to add a card.

This is the yaml:
`    card:
      type: custom:webrtc-camera
      entity: camera.doorbell`

and attached is what I see on the dashboard after saving the card.
![Web-RTC](https://user-images.githubusercontent.com/5306739/142478913-44f4f92a-a937-4adb-9a96-d0321b49c539.png)

**Comment by Protoncek** [comment]
I just went through my errors and i have a similar problem: when loading main page i get an error (in browser's F12 log):

![image](https://user-images.githubusercontent.com/26406640/142760719-9b245c80-5e7d-43e5-a43d-27000455d71c.png)

The point is that i DON'T have webrtc plugin installed anymore. I did have it a while ago. I reinstalled it, uninstalled, and same error shows. I searched my HA and i don't find any webrtc entry in my lovelace boards...

At the same time, i wonder, why file "rtsp2webrtc_v4_amd64" still exists in my HA installation after removing plugin (in root)?

Any clues what's wrong?
THX!

**Comment by AlexxIT** [comment]
@Protoncek delete js file from http://ha:8123/config/lovelace/resources and remove rtsp2webrtc file from config folder manually

**Comment by Protoncek** [comment]
Thank you a lot! Of course it "works"! I already wrote down "check resources" into my "help" list of things to check if all is not ok.

Don't get me wrong - i love(d) this plugin, because it's super fast, unlike built-in HA card, where picture can be shown, but it's almost 10 seconds behind - here it's practically instant and i used it in a combo with automatic gates opening. The reason i stopped using this plugin is because after a while my HA lovelace got pretty crowded, so i bought a second tablet for my living room and now i have two: HA on first one and video surveilance on second one (i have more cameras...), so i don't need video picture in HA anymore.

Thanks again!
Best regards , Pavel
