### ISSUE TITLE
Strange behavior - Home Assistant + Nginx inside Docker

### ISSUE THREAD

**Issue by pnt-thiago** [AlexxIT/WebRTC#174]
Hi, I am experiencing some strange behavior with my setup. Currently I have two instances of Home Assistant, in two different locations and networks, both of them are composed of a HA docker image with NGINX reverse proxy for SSL termination; both of them have fixed external IP adresses and both have cameras. The issue happens as follows:

1. The streams work very well in android using the HA APP and in the Chrome for Android - All streams uses WebRTC and everything works both locally (wifi accessing the local instance ) and remotely (4G cellphone network accessing the local instance and wifi accessing the remote one);
2. The streams do not work in the HA APP for iphone (local and remote);
3. The streams work in a windows 11 PC (tested with Firefox, Chrome and Edge) but only using MSE, they do not connect using WebRTC (local and remote);

So I performed some tests and I achieved the following results, considering the tested platforms as: 1 for Android, 2 for Iphone and 3 for Windows 11 PC...
- If I set MSE to false, 1 works and 2 and 3 do not (chrome warning: "MediaSource doesn't supported." and "WebSocket connection to 'wss://#######' failed: WebSocket is closed before the connection is established.")
- In 1 everything workes out of the box, I didn`t have to forward any UDP ports and NGINX/Docker are just exposing ports 80 and 443;
- I`ve tried to forward a range of udp ports in docker, nginx, my router and set the integration to use that range; after that 1 still works and 2 and 3 does not (3 works only using MSE).

Does any one experienced this kind of behavior?

**Comment by pnt-thiago** [comment]
Just to add: this is the error in Chrome for Windows while playing using MSE:
Uncaught DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

**Comment by AlexxIT** [comment]
Do you have problems with latest version?
https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.0

**Comment by keiranharris** [comment]
@pnt-thiago - would you be so kind as to share your relevant nginx (in docker) config. Trying to get this to work is doing my head in. 

From this article ( https://stackoverflow.com/questions/40917372/udp-forwarding-with-nginx ), It seems I need stream directive.... but that, when I try and configure in my /conf.d/*****.conf, it throws me an error: 
`nginx: [emerg] "stream" directive is not allowed here in /etc/nginx/conf.d/bex36-nginx.conf:143`

I see the reason why from here ( https://www.nginx.com/blog/load-balancing-dns-traffic-nginx-plus/ )... note the warning on that page: 
_"Warning: You cannot simply add this configuration snippet as a new file in the /etc/nginx/conf.d directory. A validation error results (“stream directive is not allowed here”), because the default NGINX Plus nginx.conf configuration file includes the content of files in the conf.d directory in the http block. The simplest solution is to include the complete stream block directly in nginx.conf."_

... makes sense. So I need the stream block one level higher up the include hierarchy. But how the heck do I edit the docker /etc/nginx/nginx.conf file.... well I mean I can of course, but won't it be destroyed each time I restart the container. How did you solve this? 

thanks in advance! 
Keiran.

**Comment by pnt-thiago** [comment]
Hi @keiranharris, I ended up abandoning nginx and using traefik instead.

**Comment by keiranharris** [comment]
Thanks @pnt-thiago - that just sent me down a research rabbit hole. Love it. I feel attached to nginx after all the love ive put into it over the years… but autodiscovery of docker services does sound nice. Any dramas to be aware of for home assistant? (And then in particular webRTC?). Any chance i could get a look at your traefik config file?

**Comment by AlexxIT** [comment]
I think you can continue your discussion in closed issue :)
