### ISSUE TITLE
How do I use camera screenshot as WebRTC Card poster before lunching stream?

### ISSUE THREAD

**Issue by luzik** [AlexxIT/WebRTC#479]
I do have a crappy internet, and while I am outside my WiFi I have to wait few seconds to WebRTC card show stream, but sometimes just simple image would be enough. I found WebRTC card have "poster" attribute. It would be awesome to use for example frame from go2rtc or maybe some HA/frigate screenshot.
How can I do it?

**Comment by dersher** [comment]
Insert your camera's snapshot URL into the poster attribute.
For example, mine (Unifi Protect cameras):
`poster: <ip-address of camera>/snap.jpeg`

You may need to enable the anonymous snapshot feature depending on your camera model.

Having said that, what I have personally observed is that the snapshot seems to be cached by the WebRTC integration, so oftentimes the poster image that is shown is the cached image and not the realtime snapshot from the camera itself.
I have tried reverse proxying the camera snapshot URL and replaced http headers to explicitly state "no-cache" but this didn't seem to have any effect.

Would be good if the realtime poster image can be pulled each time WebRTC is loading the camera feed instead of using the cached version for a more seamless interaction.

**Comment by luzik** [comment]
Thanks - your solution is quite specific for your camera. It is definitely not universal for all cameras.

**Comment by AlexxIT** [comment]
This feature available in the latest version.
If you have link to image - you need to create new go2rtc stream with this link as a source. And use this new stream as poster.
If not - just use your main camera stream as a poster.

https://github.com/AlexxIT/WebRTC#custom-card

**Comment by AlexxIT** [comment]
Click on player doesn't change stream. Your first stream is empty.

**Comment by AlexxIT** [comment]
On poster - no. You should click on stream switch. Mode name (top right corner) or stream name (bottom line in custom UI)

**Comment by exee25** [comment]
這是我的設定
type: vertical-stack
cards:
  - type: conditional
    conditions:
      - entity: input_boolean.show_webrtc_cam2
        state: 'off'
    card:
      type: picture
      entity: input_boolean.show_webrtc_cam2
      image: >-
        http://192.168.99.179:88/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=brian&pwd=Abc803727
      tap_action:
        action: call-service
        service: input_boolean.toggle
        service_data:
          entity_id: input_boolean.show_webrtc_cam2
  - type: conditional
    conditions:
      - entity: input_boolean.show_webrtc_cam2
        state: 'on'
    card:
      type: custom:webrtc-camera
      url: Gmroom_cam
      mode: webrtc
      media: video,audio,microphone
      ui: true
      muted: true
      digital_ptz: false
      title: play room

可以進入卡片時出現snapshop，點一下卡片後，開始串流
