### ISSUE TITLE
Is there a way to use it with motion and webcam?

### ISSUE THREAD

**Issue by seventhsite** [AlexxIT/WebRTC#50]
I have motion installed and one web-camera Logitech C270 in it.
Is there any way to see stream in Home assistant with this integration?

motion Version 4.2.2
stream url http://192.168.7.2:8082/0/

Of course WebRTC say "Error: support only RTSP-stream". Maybe motion can stream in RTSP?

**Comment by Papadoma** [comment]
MotionEye does this I think
It uses motion in the background

**Comment by MrTheoW** [comment]
I suppose you mean motionEye.
With motionEye you can add a local webcam (such as the Logitech you mentioned) and turn on RTSP from the settings. Then use it to do motion detection. But truth be said, motionEye is already capable to do that.
The thing is, WebRTC is very lightweight and if you only want a fast way to add a video feed to your Home Assistant I think it's best to use WebRTC because it just does that.
If you want to do motion detection, storage and a lot of other things and you don't care about the use of resources you could go for motionEye.
It just depends on what you want to accomplish.

**Comment by AlexxIT** [comment]
USB cameras supported in v3
