### ISSUE TITLE
How to add microphone mute button on interface

### ISSUE THREAD

**Issue by hoanglongutc** [AlexxIT/WebRTC#734]
Hi,
I have successfully set up 2-way audio, however there is no button to temporarily mute the microphone.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/WebRTC?tab=readme-ov-file#two-way-audio
https://github.com/AlexxIT/WebRTC?tab=readme-ov-file#custom-card

**Comment by fbalesse** [comment]
Hi,

I use successfully the 2 way audio since months and it's great and i like this componant.
Regardings the 2 links don't seems to answer the original question that interest me too.

The option "muted: true" only mute sound on device speaker, not device microphone. So sounds continue to be played on camera side.
It will me possible to have "muted-micophone: true" option ?
Even better, in addition have a shortcut "mute microphone" as the  existing shortcut "mute speaker".

Thank you.
Best regards.

**Comment by AlexxIT** [comment]
The functionality of multiple streams solves this problem better than "muted-micophone".

**Comment by supportads-COM** [comment]
Hi, Yes, it's right. Thank to this good idea.
Also possible to do this creating a switch to mute/unmute cam speaker instead of mic.

**Comment by fbalesse** [comment]
Hi, Yes, it's right. Thank to this good idea.
Also possible to do this creating a switch to mute/unmute cam speaker instead of mic.
